Repository OVAL-Community/OVAL, pull requests merged in 2024-10, with the labels that each got.

#126 Proposal to add new constructs to AIX schema
  oval-schemas/aix-definitions-schema.xsd
  oval-schemas/aix-system-characteristics-schema.xsd
Labels: Add to Existing Schema, IBM AIX

#172 Adding trustee_name back to several windows test states and items
  oval-schemas/windows-definitions-schema.xsd
  oval-schemas/windows-system-characteristics-schema.xsd
Labels: Microsoft

#149 Adding HKEY_CURRENT_USER_LOCAL_SETTINGS to EntityStateRegistryHiveType
  oval-schemas/windows-definitions-schema.xsd
Labels: Bug, Microsoft
